### ISSUE TITLE
Issue #3:

### ISSUE THREAD

**Issue by Jackus01** [hitime1234/school-hotel-project#3]
[
![image](https://user-images.githubusercontent.com/68022139/99153566-2490ed80-26a1-11eb-97fd-6c51782f7d85.png)
](url)

**Comment by hitime1234** [comment]
thanks random stranger i totally never meet before.

**Comment by Jackus01** [comment]
![image](https://user-images.githubusercontent.com/68022139/99153906-aa159d00-26a3-11eb-89f6-cbe1f05ddd3b.png)
![image](https://user-images.githubusercontent.com/68022139/99153913-b4d03200-26a3-11eb-972c-1d8c19e7d9a9.png)
![image](https://user-images.githubusercontent.com/68022139/99153916-bb5ea980-26a3-11eb-9c81-b95abe1d64b5.png)

**Comment by hitime1234** [comment]
found issue
checkouts on references after first cause issue

**Comment by Philipadelphia** [comment]
Interesting, very interesting.

**Comment by hitime1234** [comment]
we have fixed it via 1.9 main
please use release 1.9
